import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Company } from '../models/company';
import { Item } from '../models/item';

@Injectable({
  providedIn: 'root',
})
export class CompaniesService {
  private readonly http = inject(HttpClient);

  private dummyCompanies: Company[] = [
    {
      id: '1',
      name: 'Tech Solutions Ltd.',
      externalId: 'EXT001',
      surname: 'Smith',
      address: '123 Tech Park',
      phone: '+1-555-0101',
      email: 'contact@techsolutions.com',
      city: 'San Francisco',
      cityCode: 94105,
      street: 'Market Street',
      deliveryType: {
        delivery: 'Standard',
        pickUp: 'Available',
      },
      items: [
        {
          id: '101',
          companyId: '1',
          groupId: 'G1',
          name: 'Laptop X1',
          description: 'High performance laptop',
          image: 'https://placehold.co/600x400',
          price: 1200,
          highlited: true,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
        {
          id: '102',
          companyId: '1',
          groupId: 'G1',
          name: 'Wireless Mouse',
          description: 'Ergonomic wireless mouse',
          image: 'https://placehold.co/600x400',
          price: 25,
          highlited: false,
          saledPrice: true,
          available: true,
          unit: 'pcs',
        },
      ],
    },
    {
      id: '2',
      name: 'Green Grocers Inc.',
      externalId: 'EXT002',
      surname: 'Doe',
      address: '456 Green Avenue',
      phone: '+1-555-0202',
      email: 'info@greengrocers.com',
      city: 'Portland',
      cityCode: 97204,
      street: 'Oak Street',
      deliveryType: {
        delivery: 'Express',
        pickUp: 'Curbside',
      },
      items: [
        {
          id: '201',
          companyId: '2',
          groupId: 'G2',
          name: 'Organic Apples',
          description: 'Fresh organic apples',
          image: 'https://placehold.co/600x400',
          price: 3,
          highlited: true,
          saledPrice: false,
          available: true,
          unit: 'kg',
        },
        {
          id: '202',
          companyId: '2',
          groupId: 'G2',
          name: 'Carrots',
          description: 'Crunchy carrots',
          image: 'https://placehold.co/600x400',
          price: 1.5,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'kg',
        },
      ],
    },
    {
      id: '3',
      name: 'Blue Sky Logistics',
      externalId: 'EXT003',
      surname: 'Johnson',
      address: '789 Blue Blvd',
      phone: '+1-555-0303',
      email: 'support@bluesky.com',
      city: 'Seattle',
      cityCode: 98101,
      street: 'Pine Street',
      deliveryType: {
        delivery: 'Overnight',
        pickUp: 'Warehouse',
      },
      items: [
        {
          id: '301',
          companyId: '3',
          groupId: 'G3',
          name: 'Shipping Box Small',
          description: 'Durable small shipping box',
          image: 'https://placehold.co/600x400',
          price: 2,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
        {
          id: '302',
          companyId: '3',
          groupId: 'G3',
          name: 'Bubble Wrap',
          description: 'Protective bubble wrap roll',
          image: 'https://placehold.co/600x400',
          price: 15,
          highlited: true,
          saledPrice: true,
          available: true,
          unit: 'roll',
        },
      ],
    },
    {
      id: '4',
      name: 'Quantum Innovations',
      externalId: 'EXT004',
      surname: 'Williams',
      address: '101 Quantum Way',
      phone: '+1-555-0404',
      email: 'hello@quantuminnovations.com',
      city: 'Austin',
      cityCode: 73301,
      street: 'Tech Ridge',
      deliveryType: {
        delivery: 'Standard',
        pickUp: 'Available',
      },
      items: [
        {
          id: '401',
          companyId: '4',
          groupId: 'G4',
          name: 'Quantum Processor',
          description: 'Next-gen processor',
          image: 'https://placehold.co/600x400',
          price: 500,
          highlited: true,
          saledPrice: false,
          available: false,
          unit: 'pcs',
        },
        {
          id: '402',
          companyId: '4',
          groupId: 'G4',
          name: 'Cooling System',
          description: 'Advanced cooling system',
          image: 'https://placehold.co/600x400',
          price: 150,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
      ],
    },
    {
      id: '5',
      name: 'Solaris Energy',
      externalId: 'EXT005',
      surname: 'Brown',
      address: '202 Sun Lane',
      phone: '+1-555-0505',
      email: 'info@solarisenergy.com',
      city: 'Phoenix',
      cityCode: 85001,
      street: 'Sunny Blvd',
      deliveryType: {
        delivery: 'Express',
        pickUp: 'Curbside',
      },
      items: [
        {
          id: '501',
          companyId: '5',
          groupId: 'G5',
          name: 'Solar Panel',
          description: 'High efficiency solar panel',
          image: 'https://placehold.co/600x400',
          price: 300,
          highlited: true,
          saledPrice: true,
          available: true,
          unit: 'pcs',
        },
        {
          id: '502',
          companyId: '5',
          groupId: 'G5',
          name: 'Inverter',
          description: 'DC to AC inverter',
          image: 'https://placehold.co/600x400',
          price: 250,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
      ],
    },
    {
      id: '6',
      name: 'Oceanic Shipping',
      externalId: 'EXT006',
      surname: 'Davis',
      address: '303 Harbor Drive',
      phone: '+1-555-0606',
      email: 'contact@oceanicshipping.com',
      city: 'Miami',
      cityCode: 33101,
      street: 'Ocean View',
      deliveryType: {
        delivery: 'Overnight',
        pickUp: 'Port',
      },
      items: [
        {
          id: '601',
          companyId: '6',
          groupId: 'G6',
          name: 'Cargo Container',
          description: 'Standard 20ft container',
          image: 'https://placehold.co/600x400',
          price: 2000,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
        {
          id: '602',
          companyId: '6',
          groupId: 'G6',
          name: 'Pallet',
          description: 'Wooden pallet',
          image: 'https://placehold.co/600x400',
          price: 15,
          highlited: false,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
      ],
    },
    {
      id: '7',
      name: 'Mountain Gear Co.',
      externalId: 'EXT007',
      surname: 'Miller',
      address: '404 Peak Road',
      phone: '+1-555-0707',
      email: 'support@mountaingear.com',
      city: 'Denver',
      cityCode: 80201,
      street: 'High Altitude Way',
      deliveryType: {
        delivery: 'Standard',
        pickUp: 'Store',
      },
      items: [
        {
          id: '701',
          companyId: '7',
          groupId: 'G7',
          name: 'Hiking Boots',
          description: 'Waterproof hiking boots',
          image: 'https://placehold.co/600x400',
          price: 120,
          highlited: true,
          saledPrice: false,
          available: true,
          unit: 'pair',
        },
        {
          id: '702',
          companyId: '7',
          groupId: 'G7',
          name: 'Climbing Rope',
          description: 'Dynamic climbing rope',
          image: 'https://placehold.co/600x400',
          price: 180,
          highlited: false,
          saledPrice: true,
          available: true,
          unit: 'pcs',
        },
      ],
    },
    {
      id: '8',
      name: 'Urban Outfitters Ltd.',
      externalId: 'EXT008',
      surname: 'Wilson',
      address: '505 City Center',
      phone: '+1-555-0808',
      email: 'sales@urbanoutfitters.com',
      city: 'New York',
      cityCode: 10001,
      street: 'Broadway',
      deliveryType: {
        delivery: 'Express',
        pickUp: 'In-Store',
      },
      items: [
        {
          id: '801',
          companyId: '8',
          groupId: 'G8',
          name: 'Streetwear Jacket',
          description: 'Stylish streetwear jacket',
          image: 'https://placehold.co/600x400',
          price: 85,
          highlited: true,
          saledPrice: false,
          available: true,
          unit: 'pcs',
        },
        {
          id: '802',
          companyId: '8',
          groupId: 'G8',
          name: 'Sneakers',
          description: 'Comfortable sneakers',
          image: 'https://placehold.co/600x400',
          price: 95,
          highlited: false,
          saledPrice: true,
          available: true,
          unit: 'pair',
        },
      ],
    },
  ];

  getCompanies(search: string): Observable<Company[]> {
    const filter = this.dummyCompanies.filter((x) => x.name.toLowerCase().includes(search));
    return of(filter);
  }

  getCompany(id: string): Observable<Company> {
    const company = this.dummyCompanies.find((c) => c.id === id) || ({} as Company);
    return of(company);
  }
}
